### ISSUE TITLE
Missing symbol error

### ISSUE THREAD

**Issue by fener1efes2** [ryanrocket/caravel_automatic_gain_control#3]
I am trying to examine this project. 
I have installed sky water 130 nm library along with xschem, ngspice and magic.
But when I open shematic files, I cannot view them correctly, as shown below.
![image](https://user-images.githubusercontent.com/107809055/179354181-403331dd-0a2f-4c0c-83e3-bdc0108fc6cf.png)

**Comment by ryanrocket** [comment]
Right-click each symbol > edit attributes > Browse > navigate to the proper symbol
